# jekyll config
# _drafts blog
# theme partly based on: 
# Kiko-plus https://aweekj.github.io/Kiko-plus/ and Minima https://github.com/jekyll/minima

# basic
title: _drafts
description: a blog of notes, solutions, and mini-workshops to get things started.
keywords: digital humanities, tutorial, workshops, code, linux
author: EvanWill
github_username: evanwill
twitter_username: EvanPeterWill

url: https://evanwill.github.io
baseurl: /_drafts

# build
collections:
  notes:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
